// Enums do Prisma definidos localmente para type-check sem banco real
export enum PlanoTipo      { STARTER = 'STARTER', PRO = 'PRO', ENTERPRISE = 'ENTERPRISE' }
export enum TenantStatus   { AGUARDANDO = 'AGUARDANDO', ATIVO = 'ATIVO', SUSPENSO = 'SUSPENSO' }
export enum ProjetoStatus  { NAO_INICIADO='NAO_INICIADO', ATIVO='ATIVO', PAUSADO='PAUSADO', CONCLUIDO='CONCLUIDO', CANCELADO='CANCELADO' }
export enum UsuarioPerfil  { ADMIN='ADMIN', PERSONALIZADO='PERSONALIZADO' }
export enum UsuarioStatus  { ATIVO='ATIVO', INATIVO='INATIVO', CONVIDADO='CONVIDADO' }
export enum RdoStatus      { RASCUNHO='RASCUNHO', PENDENTE_APROVACAO='PENDENTE_APROVACAO', APROVADO='APROVADO', REJEITADO='REJEITADO' }
export enum AtividadeStatus { NAO_INICIADA='NAO_INICIADA', EM_ANDAMENTO='EM_ANDAMENTO', CONCLUIDA='CONCLUIDA', EM_ATRASO='EM_ATRASO' }
export enum ClimaCondicao  { SOL='SOL', NUBLADO='NUBLADO', CHUVA='CHUVA', TEMPESTADE='TEMPESTADE' }
export enum ClimaImpacto   { NENHUM='NENHUM', PARCIAL='PARCIAL', TOTAL='TOTAL' }
export enum LogNivel       { INFO='INFO', AVISO='AVISO', ERRO='ERRO', CRITICO='CRITICO' }
export enum LogCategoria   { LOGIN='LOGIN', RDO='RDO', USUARIO='USUARIO', PLANO='PLANO', EMPRESA='EMPRESA', ASSINATURA='ASSINATURA', SISTEMA='SISTEMA' }
export enum AssinaturaStatus { PENDENTE='PENDENTE', ASSINADO='ASSINADO' }
export enum OcorrenciaTipo { ACIDENTE_INCIDENTE='ACIDENTE_INCIDENTE', ATRASO_MATERIAL='ATRASO_MATERIAL', PROBLEMA_TECNICO='PROBLEMA_TECNICO', PARALISACAO='PARALISACAO', CONDICAO_CLIMATICA='CONDICAO_CLIMATICA', FALTA_MAO_DE_OBRA='FALTA_MAO_DE_OBRA', OUTRO='OUTRO' }
export enum OcorrenciaGravidade { BAIXA='BAIXA', MEDIA='MEDIA', ALTA='ALTA', CRITICA='CRITICA' }
export enum MidiaTipo      { FOTO='FOTO', VIDEO='VIDEO', ARQUIVO='ARQUIVO' }
export enum MaoDeObraCategoria { DIRETA='DIRETA', INDIRETA='INDIRETA', TERCEIRIZADO='TERCEIRIZADO' }
export enum EquipamentoTipo { PROPRIO='PROPRIO', ALUGADO='ALUGADO', TERCEIRIZADO='TERCEIRIZADO' }
export enum ProjetoAcessoNivel { VISUALIZAR='VISUALIZAR', EDITAR='EDITAR', GERENCIAMENTO='GERENCIAMENTO' }
export enum ProjetoAssinaturaModo { ABERTA='ABERTA', DEFINIDA='DEFINIDA' }
